#remote_theme: pages-themes/architect@v0.2.0
#remote_theme: pages-themes/hacker
remote_theme: pages-themes/slate
#remote_theme: pages-themes/tactile
plugins:
  - jekyll-remote-theme

title: Data Gator
description: Documentation for the Data Gator sensor network solution.
